[package]
name = "d2s5"
version = "0.1.0"
authors = ["Dark Silkmaster"]

[dependencies]
hyper = "0.11.6"
error-chain = "0.10"
futures = "0.1"
tokio-core = "0.1"
tokio-service = "0.1"
tokio-proto = "0.1"
tokio-signal = "0.1"
serde = "0.9"
serde_derive = "0.9"
env_logger = "0.4"
log = "0.3"
